APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:jUOVMzS38fxWlj0faw7GqB+tELiRAFyb8lxUaTMFN5Y=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=pandutest_rzb
DB_USERNAME=pandutest_user
DB_PASSWORD=27272727pandu
DB_TABLE_PREFIX=tb_

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp-pulse.com
MAIL_PORT=465
MAIL_USERNAME=admin@mayaapp.co
MAIL_PASSWORD=RNPZFi8sf3NGk
MAIL_ENCRYPTION=ssl

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1
